Repository wecode-bootcamp-korea/westagram-frontend, pull requests merged in 2020-08, with the labels that each got.

#65 [유휘찬 ] Add: 로그인, 메인페이지 레이아웃 및 기능구현
  students/11th/YUhwichan/img/logo_text.png
  students/11th/YUhwichan/index.html
  students/11th/YUhwichan/js/login.js
  students/11th/YUhwichan/js/main.js
  students/11th/YUhwichan/login.html
  students/11th/YUhwichan/main.html
  students/11th/YUhwichan/style/common.css
  students/11th/YUhwichan/style/login.css
  students/11th/YUhwichan/style/main.css
  students/11th/YUhwichan/tobe/login.png
  students/11th/YUhwichan/tobe/main.png
  students/11th/YUhwichan/tobe/main_layout.png
Labels: Status: Accepted, 필수 구현 사항

#61 [한태규] Add: 필수 구현 사항 완료
  students/11th/hanteagyu/img/3146790-256.png
  students/11th/hanteagyu/img/app store.png
  students/11th/hanteagyu/img/bookmark.png
  students/11th/hanteagyu/img/compass.png
  students/11th/hanteagyu/img/empty face.png
  students/11th/hanteagyu/img/google play.png
  students/11th/hanteagyu/img/heart.png
  students/11th/hanteagyu/img/home.png
  students/11th/hanteagyu/img/logo_text.png
  students/11th/hanteagyu/img/phone photo1.jpg
  students/11th/hanteagyu/img/phone photo2.jpg
  students/11th/hanteagyu/img/phone photo3.jpg
  students/11th/hanteagyu/img/phone photo4.jpg
  students/11th/hanteagyu/img/phone photo5.jpg
  students/11th/hanteagyu/img/phone.png
  students/11th/hanteagyu/img/plane.png
  students/11th/hanteagyu/img/reactionheart.png
  students/11th/hanteagyu/img/reactionpaperplane.png
  students/11th/hanteagyu/img/reactiontalkbox.png
  students/11th/hanteagyu/img/점점점.png
  students/11th/hanteagyu/js/login.js
  students/11th/hanteagyu/js/main.js
  students/11th/hanteagyu/login.html
  students/11th/hanteagyu/main.html
  students/11th/hanteagyu/style/common.css
  students/11th/hanteagyu/style/login.css
  students/11th/hanteagyu/style/main.css
  students/11th/hanteagyu/style/phone photo1.jpg
  students/11th/hanteagyu/style/phone photo2.jpg
  students/11th/hanteagyu/style/phone photo3.jpg
  students/11th/hanteagyu/style/phone photo4.jpg
  students/11th/hanteagyu/style/phone photo5.jpg
  students/11th/hanteagyu/style/phone.png
Labels: Status: Accepted, 필수 구현 사항

#52 [김동호] ADD: 로그인 페이지 레이아웃 구현
  students/11th/README.md
  students/11th/donghokim/img/logo_text.png
  students/11th/donghokim/js/login.js
  students/11th/donghokim/js/main.js
  students/11th/donghokim/login.html
  students/11th/donghokim/main.html
  students/11th/donghokim/style/common.css
  students/11th/donghokim/style/login.css
  students/11th/donghokim/style/main.css
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중, 필수 구현 사항

#55 [이상훈]Add: 필수구현사항 구현
  students/11th/sanghunlee/img/applelogo.png
  students/11th/sanghunlee/img/deletebtn.png
  students/11th/sanghunlee/img/dog.jpeg
  students/11th/sanghunlee/img/fblogo.png
  students/11th/sanghunlee/img/googlelogo.png
  students/11th/sanghunlee/img/howl.jpg
  students/11th/sanghunlee/img/howl2.jpeg
  students/11th/sanghunlee/img/instagram.ico
  students/11th/sanghunlee/img/lbb.jpeg
  students/11th/sanghunlee/img/leftiamge.png
  students/11th/sanghunlee/img/logo_text.png
  students/11th/sanghunlee/img/magnifier.png
  students/11th/sanghunlee/img/redherat.jpeg
  students/11th/sanghunlee/img/wecode.jpeg
  students/11th/sanghunlee/js/login.js
  students/11th/sanghunlee/js/main.js
  students/11th/sanghunlee/login.html
  students/11th/sanghunlee/main.html
  students/11th/sanghunlee/style/login.css
  students/11th/sanghunlee/style/main.css
Labels: Status: Accepted

#53 [황연욱] Add: HTML, CSS, JS 필수구현사항 구현완료, 추가기능 구현
  students/11th/yeonukhwang/README.md
  students/11th/yeonukhwang/img/avatar-yeonuk.jpg
  students/11th/yeonukhwang/img/backend.jpg
  students/11th/yeonukhwang/img/bookmark.png
  students/11th/yeonukhwang/img/commentbubble.png
  students/11th/yeonukhwang/img/compass.png
  students/11th/yeonukhwang/img/del.png
  students/11th/yeonukhwang/img/feed2.png
  students/11th/yeonukhwang/img/feedimg.jpeg
  students/11th/yeonukhwang/img/frontend.jpg
  students/11th/yeonukhwang/img/heart.png
  students/11th/yeonukhwang/img/javacsript.png
  students/11th/yeonukhwang/img/logo.png
  students/11th/yeonukhwang/img/logo_text.png
  students/11th/yeonukhwang/img/main__left.png
  students/11th/yeonukhwang/img/mypage.png
  students/11th/yeonukhwang/img/redheart.png
  students/11th/yeonukhwang/img/share.png
  students/11th/yeonukhwang/img/ssalguksoo.JPG
  students/11th/yeonukhwang/img/storypp1.jpg
  students/11th/yeonukhwang/img/storypp2.jpg
  students/11th/yeonukhwang/img/storypp3.jpg
  students/11th/yeonukhwang/img/storypp4.jpg
  students/11th/yeonukhwang/img/storypp5.jpg
  students/11th/yeonukhwang/img/threedots.png
  students/11th/yeonukhwang/img/wecodeimg.png
  students/11th/yeonukhwang/js/login.js
  students/11th/yeonukhwang/js/main.js
  students/11th/yeonukhwang/login.html
  students/11th/yeonukhwang/main.html
  students/11th/yeonukhwang/style/common.css
  students/11th/yeonukhwang/style/login.css
  students/11th/yeonukhwang/style/main.css
Labels: Status: 수정 요청, Status: 추가 기능 구현중, 필수 구현 사항

#45 [강예지] Refactor : 코드 리팩토링( 멘토리뷰 반영, 불필요한 코드 제거 )
  students/11th/yejikang/img/107076099_189778595916222_2635888378644807428_n.jpg
  students/11th/yejikang/img/feedsProfile.jpg
  students/11th/yejikang/img/logo_text.png
  students/11th/yejikang/img/me.jpg
  students/11th/yejikang/js/login.js
  students/11th/yejikang/js/main.js
  students/11th/yejikang/login.html
  students/11th/yejikang/main.html
  students/11th/yejikang/style/common.css
  students/11th/yejikang/style/login.css
  students/11th/yejikang/style/main.css
Labels: Status: Accepted

#59 [김건우]Add: 로그인 페이지, 메인 페이지 필수구현 미션 적용
  students/11th/KimGeonWoo/img/logo_text.png
  students/11th/KimGeonWoo/img/mimi.png
  students/11th/KimGeonWoo/js/login.js
  students/11th/KimGeonWoo/js/main.js
  students/11th/KimGeonWoo/login.html
  students/11th/KimGeonWoo/main.html
  students/11th/KimGeonWoo/style/login.css
  students/11th/KimGeonWoo/style/main.css
Labels: Status: 리뷰 요청, 필수 구현 사항

#66 [이영섭] ADD : 필수 구현사항 및 보너스 구현 항목 추가
  students/11th/yeongseoblee/img/9364675fb26a.png
  students/11th/yeongseoblee/img/logo_text.png
  students/11th/yeongseoblee/js/login.js
  students/11th/yeongseoblee/js/main.js
  students/11th/yeongseoblee/login.html
  students/11th/yeongseoblee/main.html
  students/11th/yeongseoblee/style/common.css
  students/11th/yeongseoblee/style/login.css
  students/11th/yeongseoblee/style/main.css
Labels: Status: Accepted, 추가 구현 사항, 필수 구현 사항

#78 [12기 권영빈] Add: 필수 구현 사항 및 추가 구현 사항
  students/12th/youngbinkwon/img/1.jpg
  students/12th/youngbinkwon/img/10.jpg
  students/12th/youngbinkwon/img/11.jpg
  students/12th/youngbinkwon/img/12.jpg
  students/12th/youngbinkwon/img/13.jpg
  students/12th/youngbinkwon/img/14.jpg
  students/12th/youngbinkwon/img/15.jpg
  students/12th/youngbinkwon/img/16.jpg
  students/12th/youngbinkwon/img/17.jpg
  students/12th/youngbinkwon/img/18.jpg
  students/12th/youngbinkwon/img/19.jpg
  students/12th/youngbinkwon/img/2.png
  students/12th/youngbinkwon/img/3.jpg
  students/12th/youngbinkwon/img/4.jpg
  students/12th/youngbinkwon/img/5.jpg
  students/12th/youngbinkwon/img/6.jpg
  students/12th/youngbinkwon/img/7.jpg
  students/12th/youngbinkwon/img/8.jpg
  students/12th/youngbinkwon/img/9.jpg
  students/12th/youngbinkwon/img/appAndroid.png
  students/12th/youngbinkwon/img/appIOS.png
  students/12th/youngbinkwon/img/background.png
  students/12th/youngbinkwon/img/background2.png
  students/12th/youngbinkwon/img/loginImage3.jpg
  students/12th/youngbinkwon/img/login_background1.png
  students/12th/youngbinkwon/img/loginimage1.jpg
  students/12th/youngbinkwon/img/loginimage2.jpg
  students/12th/youngbinkwon/img/logo_text.png
  students/12th/youngbinkwon/img/search.png
  students/12th/youngbinkwon/js/login.js
  students/12th/youngbinkwon/js/main.js
  students/12th/youngbinkwon/js/main_search.js
  students/12th/youngbinkwon/login.html
  students/12th/youngbinkwon/main.html
  students/12th/youngbinkwon/style/common.css
  students/12th/youngbinkwon/style/login.css
  students/12th/youngbinkwon/style/main.css
Labels: Status: 리뷰 요청

#87 [12기 문상호] Refactor: 멘토 리뷰 반영 / Add: 댓글 기능 추가
  students/12th/sanghomoon/img/contentsBox/bookmark.png
  students/12th/sanghomoon/img/contentsBox/comment.png
  students/12th/sanghomoon/img/contentsBox/heart.png
  students/12th/sanghomoon/img/contentsBox/share.png
  students/12th/sanghomoon/img/defaultProfile.jpg
  students/12th/sanghomoon/img/dm.png
  students/12th/sanghomoon/img/explore.png
  students/12th/sanghomoon/img/favicon.png
  students/12th/sanghomoon/img/feedsHeaderMenu.png
  students/12th/sanghomoon/img/heart.png
  students/12th/sanghomoon/img/home.png
  students/12th/sanghomoon/img/instagram.png
  students/12th/sanghomoon/img/logo_text.png
  students/12th/sanghomoon/img/profile.jpg
  students/12th/sanghomoon/img/recommendList/defaultProfile.jpg
  students/12th/sanghomoon/img/recommendList/recommend1.jpg
  students/12th/sanghomoon/img/recommendList/recommend2.jpg
  students/12th/sanghomoon/img/recommendList/recommend3.jpg
  students/12th/sanghomoon/img/search-icon.png
  students/12th/sanghomoon/img/story/wecode.jpg
  students/12th/sanghomoon/img/story/광희.jpg
  students/12th/sanghomoon/img/story/류준열.jpg
  students/12th/sanghomoon/img/story/여행에미치다.jpg
  students/12th/sanghomoon/img/story/유재석.jpg
  students/12th/sanghomoon/img/story/이광수.jpg
  students/12th/sanghomoon/img/story/이효리.jpg
  students/12th/sanghomoon/img/wecode12th.jpg
  students/12th/sanghomoon/js/login.js
  students/12th/sanghomoon/js/main.js
  students/12th/sanghomoon/login.html
  students/12th/sanghomoon/main.html
  students/12th/sanghomoon/style/common.css
  students/12th/sanghomoon/style/login.css
  students/12th/sanghomoon/style/main.css
Labels: Status: 도움 요청, Status: 리뷰 요청

#91 [12기 박남준] 멘토리뷰 반영(08/28) Fix: login.css main.css login.html 수정 Refactor: login.js
  students/12th/namjunpark/img/4a5c9d62d51b.png
  students/12th/namjunpark/img/64219646_866712363683753_7365878438877462528_n.jpg
  students/12th/namjunpark/img/f155b664a93b.png
  students/12th/namjunpark/img/heart-1348868.svg
  students/12th/namjunpark/img/heart-png-8.png
  students/12th/namjunpark/img/images.png
  students/12th/namjunpark/img/instagramimg/0a2d3016f375.jpg
  students/12th/namjunpark/img/instagramimg/842fe5699220.jpg
  students/12th/namjunpark/img/instagramimg/d6bf0c928b5a.jpg
  students/12th/namjunpark/img/instagramimg/f0c687aa6ec2.jpg
  students/12th/namjunpark/img/instagramimg/phoneimg.png
  students/12th/namjunpark/img/logo_text.png
  students/12th/namjunpark/img/main/1.jpg
  students/12th/namjunpark/img/main/10.jpg
  students/12th/namjunpark/img/main/11.jpg
  students/12th/namjunpark/img/main/12.jpg
  students/12th/namjunpark/img/main/2.jpg
  students/12th/namjunpark/img/main/3.jpg
  students/12th/namjunpark/img/main/4.jpg
  students/12th/namjunpark/img/main/5.jpg
  students/12th/namjunpark/img/main/6.jpg
  students/12th/namjunpark/img/main/7.jpg
  students/12th/namjunpark/img/main/735145cfe0a4.png
  students/12th/namjunpark/img/main/8.jpg
  students/12th/namjunpark/img/main/9.jpg
  students/12th/namjunpark/img/main/bookmark.png
  students/12th/namjunpark/img/main/comment.png
  students/12th/namjunpark/img/main/dm.png
  students/12th/namjunpark/img/main/explore.png
  students/12th/namjunpark/img/main/heart.png
  students/12th/namjunpark/img/main/home.png
  students/12th/namjunpark/img/main/more.png
  students/12th/namjunpark/img/main/profile.png
  students/12th/namjunpark/img/main/share.png
  students/12th/namjunpark/img/main/unnamed.jpg
  students/12th/namjunpark/img/space-4888643_1920.jpg
  students/12th/namjunpark/img/빈하트.png
  students/12th/namjunpark/js/login.js
  students/12th/namjunpark/js/main.js
  students/12th/namjunpark/login.html
  students/12th/namjunpark/main.html
  students/12th/namjunpark/readme.md
  students/12th/namjunpark/style/common.css
  students/12th/namjunpark/style/login.css
  students/12th/namjunpark/style/main.css
  students/12th/namjunpark/style/reset.css
Labels: Status: 리뷰 요청

#75 [12기 정원태] Refactor : 멘토 리뷰 사항 반영
  .vscode/settings.json
  students/12th/wontaejeong/img/dm.png
  students/12th/wontaejeong/img/heart.png
  students/12th/wontaejeong/img/heart_clicked.png
  students/12th/wontaejeong/img/home.png
  students/12th/wontaejeong/img/logo.png
  students/12th/wontaejeong/img/logo_text.png
  students/12th/wontaejeong/img/wecode.jpg
  students/12th/wontaejeong/js/login.js
  students/12th/wontaejeong/js/main.js
  students/12th/wontaejeong/login.html
  students/12th/wontaejeong/main.html
  students/12th/wontaejeong/styles/common.css
  students/12th/wontaejeong/styles/login.css
  students/12th/wontaejeong/styles/main.css
Labels: Status: 리뷰 요청

#77 [12기 이지형] Refactor: 이슈 해결 및 멘토 리뷰 반영
  students/12th/leejihyung/img/cancel.png
  students/12th/leejihyung/img/dm.png
  students/12th/leejihyung/img/favicon.png
  students/12th/leejihyung/img/home.png
  students/12th/leejihyung/img/liked.png
  students/12th/leejihyung/img/logo_text.png
  students/12th/leejihyung/js/login.js
  students/12th/leejihyung/js/main.js
  students/12th/leejihyung/login.html
  students/12th/leejihyung/main.html
  students/12th/leejihyung/style/common.css
  students/12th/leejihyung/style/login.css
  students/12th/leejihyung/style/main.css
  tobe/login.png
  tobe/main.png
  tobe/main_layout.png
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중
